AWSTemplateFormatVersion: '2010-09-09'
Description: Route53 for Request Validator

Parameters:
  RestApiName:
    Type: String
  Lambda:
    Type: String
  LambdaArn:
    Type: String
  Environment:
    Type: String

Resources:
  RestApi:
    Properties:
      Description: Rest api
      Name: !Ref RestApiName
    Type: AWS::ApiGateway::RestApi

  ApiGatewayResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId:
        Ref: RestApi
      ParentId:
        Fn::GetAtt:
        - RestApi
        - RootResourceId
      PathPart: !Ref RestApiName

  ResourceMethodPOST:
    DependsOn:
    - ApiGatewayResource
    Type: AWS::ApiGateway::Method
    Properties:
      ResourceId:
        Ref: ApiGatewayResource
      RestApiId:
        Ref: RestApi
      ApiKeyRequired: false
      AuthorizationType: NONE
      HttpMethod: POST
      MethodResponses:
      - StatusCode: 200
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS
        IntegrationResponses:
        - StatusCode: 200
        Uri:
          Fn::Join:
          - ''
          - - 'arn:aws:apigateway:'
            - Ref: AWS::Region
            - ":lambda:path/2015-03-31/functions/"
            - !Ref LambdaArn
            - "/invocations"

  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: RestApi
      StageName: v1
    DependsOn:
    - ResourceMethodPOST

  APILambdaPermission:
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: Lambda
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
        - ''
        - - 'arn:aws:execute-api:'
          - Ref: AWS::Region
          - ":"
          - Ref: AWS::AccountId
          - ":"
          - Ref: RestApi
          - "/*"
    Type: AWS::Lambda::Permission

  APIStage:
    Properties:
      CacheClusterEnabled: false
      DeploymentId:
        Ref: ApiGatewayDeployment
      RestApiId:
        Ref: RestApi
      StageName:
        Ref: Environment
    Type: AWS::ApiGateway::Stage

Outputs:
  RootUrl:
    Description: Root URL of the API gateway
    Value:
      Fn::Join:
      - ''
      - - https://
        - Ref: RestApi
        - ".execute-api."
        - Ref: AWS::Region
        - ".amazonaws.com"
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-endpoint"