AWSTemplateFormatVersion: '2010-09-09'
Description: Route53 for Request Validator
Parameters:
  Route53CNAME:
    Description: 'CNAME to associate with request validator'
    Type: String
  HostedZoneId:
    Type: String
    Description: Route 53 hosted zone id
  Endpoint:
    Type: String

Resources:
  Route53Record:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId:
          Ref: HostedZoneId
        Name:
          Ref: Route53CNAME
        Type: CNAME
        TTL: "30"
        ResourceRecords:
          - !Ref Endpoint
Outputs:
  ApiGatewayDNS:
    Description: request validator dns
    Value:
      Ref: Route53CNAME
